name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend-poketensor
        file: ./backend-poketensor/conf/docker/Dockerfile
        push: true
        platforms: linux/amd64
        tags: simotrevi/poketensor-backend:latest
        cache-from: type=registry,ref=simotrevi/poketensor-backend:latest
        cache-to: type=inline

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-poketensor
        file: ./frontend-poketensor/docker/Dockerfile
        push: true
        platforms: linux/amd64
        tags: simotrevi/poketensor-frontend:latest
        cache-from: type=registry,ref=simotrevi/poketensor-frontend:latest
        cache-to: type=inline
